<?xml version="1.0"?>
<robot name="support" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="support_length" value="0.1" />
  <xacro:property name="support_radius" value="0.01" />
  <xacro:property name="support_offset_x" value="0.4" />
  <xacro:property name="support_offset_y" value="0.0" />
  <xacro:property name="support_offset_z" value="${support_length / 2}" />
  <xacro:property name="support_mass" value="0.5" />

  <xacro:macro name="cylinder_inertial_matrix" params="m r h">
    <inertial>
       <mass value="${m}" />
       <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
            iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
            izz="${m*r*r/2}" />     
       </inertial>
  </xacro:macro>

  <link name="support">
    <visual>
        <geometry>
            <cylinder radius="${support_radius}" length="${support_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="dark_grey" />
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${support_radius}" length="${support_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertial_matrix m="${support_mass}" r="${support_radius}" h="${support_length}" />
    </link>

  <joint name="support2mid_mount" type="fixed">
    <parent link="mid_mount" />
    <child link="support" />
    <origin xyz="${support_offset_x} ${support_offset_y} ${support_offset_z}" />
  </joint>

  <gazebo reference="support">
        <material>Gazebo/DarkGrey</material>
  </gazebo>
</robot>